// JavaScript Document

var des0 = ""
var des1 = "<img src='../../picts/triangle_black_small.png'>  <i>SOCLE ENTERRÉ À ABONNÉES HARCELANTES</i>, 2007<br />Édition<br />imprimé à l'École nationale des beaux-arts de Lyon<br />Tirage offset sur papier côtelé 250g pour la couverture,<br />papier Conqueror 100g pour le corps du livre<br />90 pages, 17 x 11,5 cm, 25 exemplaires"
var des2 = "<img src='../../picts/triangle_black_small.png'>  <i>YOU ARE NOT THE LEADERS OF THE FUTURE<br/>AND YOU NEVER WILL BE</i>, 2008<br />Installation in situ<br />Tubes de canalisation, papier glacé, affiches perforées,<br />caisson lumineux<br />Dimensions variables";
var des3 = "<img src='../../picts/triangle_black_small.png'>  <i>DISABLED</i>, 2008<br />Installation in situ<br />Tubes de métal, plaques d'aluminium, résine polyester,<br />vitres teintées, caissons lumineux<br />Dimensions variables";
var des4 = "<img src='../../picts/triangle_black_small.png'>  <i>ÉQUILATÉRAL</i>, 2009<br />Installation in situ<br />Barre en acier découpée sur mesure<br />et encastrée d'une extrémité à l'autre de l'espace,<br>formant un angle droit entre l'arête oblique et l'arête au sol<br />820 x 630 cm";
var des5 = "<img src='../../picts/triangle_black_small.png'>  <i>RECOIN</i>, 2009<br />Installation<br />Tubes de métal, attaches<br />400 cm de longueur";
var des6 = "<img src='../../picts/triangle_black_small.png'>  <i>EXTRÊME REBORD</i>, 2009<br />Installation<br />Cimaise d'exposition entourée d'une main courante en métal<br />350 x 400 x 65 cm";
var des7 = "<table width='100%' border='0' cellspacing='0' cellpadding='0'><tr><td class='text_11'><img src='../../picts/triangle_black_small.png'>&nbsp;&nbsp;<i>253 VARIATIONS AUTOUR D'UNE EFFERVESCENCE &lambda;</i>, 2009<br />Livre<br />Édition <i>Cahier des Charges</i>, imprimé à l'École nationale des beaux-arts de Lyon<br />Tirage offset sur papier Conqueror vergé 220g pour la couverture,<br />papier Smooth satin 120g pour le corps du livre<br />et papier Conqueror vergé gris pour les index<br />80 pages, 30 exemplaires</td></tr><tr><td class='spacer8'>&nbsp;</td></tr><tr><td class='text_11'><a class='link_light11' href='../../picts/2.pieces/7.253_variations/clemencetorres_publications_253_variations_autour_d_une_effervescence_lambda_pages_1_a_10.pdf' target='_blank'><img src='../../picts/more.jpg' height='20'>  Télécharger un extrait du livre, pages 1 à 10</a></td></tr></table>";
var des8 = "<table width='100%' border='0' cellspacing='0' cellpadding='0'><tr><td class='text_11'><img src='../../picts/triangle_black_small.png'>  <i>J'Y, EN METTRAIS MA TÊTE</i>, 2009<br />Édition<br />Imprimé à l'École nationale des beaux-arts de Lyon<br />Tirage offset sur papier Cyclus 100g, 30 exemplaires<br />Affiche marouflée sur mur d'exposition<br />100 x 70 cm</td></tr><tr><td class='spacer8'>&nbsp;</td></tr><tr><td class='text_11'><a class='link_light11' href='../../picts/2.pieces/8.j_en_mettrais_ma_tete/clemencetorres_publications_j_y_en_mettrais_ma_tete.pdf' target='_blank'><img src='../../picts/more.jpg' height='20'>  Télécharger l'affiche</a></td></tr></table>";
var des9 = "<img src='../../picts/triangle_black_small.png'>  <i>UPSIDE DOWN</i>, 2009<br />Installation<br />Cimaise d'exposition renversée sur l'une de ses faces<br />350 x 400 x 65 cm";
var des10 = "<img src='../../picts/triangle_black_small.png'>  <i>REAR WINDOW</i>, 2009<br />Installation in situ<br />Intérieur d'une cimaise d'exposition<br>éclairé par des tubes fluorescents,<br />vitre transparente en plexiglass<br />350 x 400 x 65 cm";
var des11 = "<img src='../../picts/triangle_black_small.png'>  <i>LIMITE PROPRE</i>, 2009<br />Installation<br />Mur d'exposition repeint<br>avec un liant vinylique transparent pour peinture<br />Niveau du recouvrement du mur<br>correspondant aux limites physiques de l'artiste,<br />220 cm de hauteur<br />220 x 750 cm";
var des12 = "<table width='100%' border='0' cellspacing='0' cellpadding='0'><tr><td class='text_11'><img src='../../picts/triangle_black_small.png'>  <i>PRÉFABRIQUÉS, ÉTHIQUE D'UNE COMMUNICATION STRATÉGIQUE ( x ; y )</i>, 2009<br />Édition<br />Imprimé à l'École nationale des beaux-arts de Lyon<br />Tirage offset sur papier Opale 220g pour la couverture,<br />papier Smooth satin 160g pour le corps du livre<br />et papier Conqueror Vergé gris 100g pour les index<br />50 pages, 22,5 x 15 cm, 30 exemplaires</td></tr><tr><td class='spacer8'>&nbsp;</td></tr><tr><td class='text_11'><a class='link_light11' href='../../picts/2.pieces/12.prefabriques/clemencetorres_publications_prefabriques_pages_1_a_10.pdf' target='_blank'><img src='../../picts/more.jpg' height='20'>  Télécharger un extrait du livre, pages 1 à 10</a></td></tr></table>";
var des13 = "<img src='../../picts/triangle_black_small.png'>  <i>PREFABRIQUÉS</i>, 2009<br />Installation<br><br>Présentoir<br>Armoire industrielle découpée, tube fluorescent<br>165 x 100 x 35 cm <br><br>Édition<br>Livre, <i>Préfabriqués, éthique d’une communication (x ; y)</i><br>Imprimé à l'École nationale des beaux-arts de Lyon<br />Tirage offset sur papier Opale 220g pour la couverture,<br>papier Smooth satin 160g pour le corps du livre <br>et papier Conqueror Vergé gris 100g pour les index<br>50 pages, 30 exemplaires";
var des14 = "<img src='../../picts/triangle_black_small.png'>  <i>PASSAGE, Faire faire le tour</i>, 2009<br />Installation<br>Tubes de métal, attaches, vitre en plexiglass,<br>tubes fluorescents, écran plat avec inscription<br>1 700 cm de long";
var des15 = "<img src='../../picts/triangle_black_small.png'>  <i>DÉCOUPES</i>, 2009 - 2010<br />Installation<br>Armoires industrielles découpées, tubes fluorescents<br>230 x 65 x 150 cm, 200 x 35 x 30 cm, 60 x 100 x 45 cm";
var des16 = "<img src='../../picts/triangle_black_small.png'>  <i>PUNCTUATION</i>, 2009<br />Installation<br>Tube de métal, moteur <br>faisant monter et descendre la barre de 7 cm<br>à hauteur des yeux de manière presque imperceptible<br>12 cm de diamètre, 400 cm de hauteur";
var des17 = "<img src='../../picts/triangle_black_small.png'>  <i>DEUX-EN-UN</i>, 2009<br />Sculpture<br>Miroir, socle en medium adapté à la ligne de démarcation<br>entre la surface miroir et la surface dépolie<br>110 x 165 x 0,6 cm";
var des18 = "<img src='../../picts/triangle_black_small.png'>  <i>FAÇADES</i>, 2010<br />Sculpture<br>Trois verres trempés, main courante en métal<br>70 x 168 x 120 cm";
var des19 = "<img src='../../picts/triangle_black_small.png'>  <i>MES ÉTALONS</i>, 2009<br />Sculpture<br>Barre en métal chromé<br>et son moulage en cire microcristalline blanche<br>Dimensions en fonction de la brassée de l'artiste,<br>168 cm";
var des20 = "<img src='../../picts/triangle_black_small.png'>  <i>TOPOLOGIE D’UN COMPORTEMENT EXTENSIBLE</i>, 2010<br />Dessin encadré<br>Crayon, collages, papier calque<br>47 x 38 cm";
var des21 = "<img src='../../picts/triangle_black_small.png'>  <i>FAÇADES, SECONDE</i>, 2010<br />Sculpture<br>Cinq verres trempés, main courante en métal<br>70 x 168 x 150 cm<br>Courtesy Nathalie Miltat, Paris";
var des22 = "<img src='../../picts/triangle_black_small.png'>  <i>TOISE</i>, 2011<br>Sculptures, 1/5<br>Métal, système téléscopique<br>Dimension variable selon le déploiement de la toise<br>par rapport à la hauteur sous plafond (max. 5m)"
var des23 = "<img src='../../picts/triangle_black_small.png'>  <i>LA MAÎTRISE DE LA DIAGONALE</i>, 2011<br>Installation in situ, miroir, câblage, poulie, métal<br>Dimensions variables<br>Courtesy Nathalie Miltat, Paris"
var des24 = "<img src='../../picts/triangle_black_small.png'>  <i>PROFONDS, MATS, ÉCLATANTS</i>, 2011<br>Série de dessins encadrés, papiers divers, collages<br>47 x 38 cm"
var des25 ="<img src='../../picts/triangle_black_small.png'>  <i>POINT DE FUITE POINTÉ</i>, 2011<br>Judas pour porte encadré<br>48 x 59 cm"
var des26 ="<img src='../../picts/triangle_black_small.png'>  <i>INTROSPECTION</i>, 2011<br>Sculpture, 3 parois de verre trempé avec argenture,<br>main courante en métal<br>80 x 80 x 168 cm"
var des27 ="<img src='../../picts/triangle_black_small.png'>  <i>BALANCEMENT DE LA LIGNE</i>, 2011<br>Installation in situ<br>Miroir dépoli sur toute sa surface à l’exception<br>d’une bande de 4 cm (représentant la hauteur du regard de l’artiste)<br>et tenu en équilibre sur sa tranche<br>par le contrepoids d'un second miroir<br>2 miroirs (168 x 70 cm chacun), câblage, poulie, métal<br>Dimensions variables"
var des28 = "<img src='../../picts/triangle_black_small.png'>  <i>BELVÉDÈRE</i>, 2011<br>Sculpture<br>4 verres trempés (168 x 70cm), main courante en métal<br>2m d'envergure<br>Avec le soutien de La BF15, Lyon (2011)<br>et l'aide généreuse de Thibault Levasseur"
var des29 ="<img src='../../picts/triangle_black_small.png'>  <i>COMMUNES MESURES</i>, 2011<br>Sculpture<br>8 tables servant de support à 8 moulages,<br>représentant les 8 distances sociales<br>définies par l’anthropologue américain Edward T.Hall,<br>selon la notion de proxémie (distance interculturelle entre les individus)<br>8 tables en métal (110 x 40 x 90 cm chacune),<br>carton, texte au mur et moulages en argile,<br>plâtre, bois, paraffine, verre, béton, acier<br>Dimensions variables (environ 9m de longueur)"
var des30 ="<table width='100%' border='0' cellspacing='0' cellpadding='0'><tr><td class='text_11'><img src='../../picts/triangle_black_small.png'>&nbsp;&nbsp;<i>SUJET(S), PRINCIPES DE D&Eacute;PLOIEMENT RELATIONNEL,<br>ENTRE LE STATIQUE ET L’&Eacute;VOLUTIF STRAT&Eacute;GIQUE</i>, 2011<br>&Eacute;dition - Livre<br>Tirage offset sur papier Popset tourterelle 220g pour la couverture,<br>papier Cyclus 110g pour le corps du livre<br>70 pages, 100 exemplaires num&eacute;rot&eacute;s<br><br>R&eacute;alis&eacute; grâce au soutien<br>de l’&Eacute;cole nationale sup&eacute;rieure des beaux-arts de Lyon :<br>Sarah Br&eacute;assier, C&eacute;cile Mazoyer, David Poissenot,<br>Yves Robert, Nicolas Romarie,<br>Joël Tardy, Emmanuel Tibloux,<br>et à la g&eacute;n&eacute;reuse contribution de Perrine Lacroix,<br>Florence Meyssonnier et Paul Lugagne Delpon</td></tr><tr><td class='spacer8'>&nbsp;</td></tr><tr><td class='text_11'><a class='link_light11' href='../../picts/2.pieces/30.sujets/clemencetorres_sujets_pages_1_a_10.pdf' target='_blank'><img src='../../picts/more.jpg' height='20'>&nbsp;&nbsp;T&eacute;l&eacute;charger un extrait du livre, pages 1 &agrave; 10</a></td></tr></table>"
var des31 ="<img src='../../picts/triangle_black_small.png'>  <i>ALIGNEMENT DES ESQUISSES PERSPECTIVES</i>, 2012<br>Installation<br>2 panneaux de verre trempé (157 x 75 cm) avec projection d'argenture,<br>miroir (157 x 75 cm), peinture, câblage<br>Avec le soutien du Palais de Tokyo"
var des32 ="<img src='../../picts/triangle_black_small.png'>  <i>ARCHÉOLOGIE D'UN PAYSAGE AVEUGLE</i>, 2012<br>Sculpture<br>Instruments d'optique en verre soufflé (judas, loupe, jumelles, longue vue),<br>support en verre et métal (157 cm de hauteur, représentant la hauteur<br>de regard de l'artiste). Avec le soutien du Palais de Tokyo,<br>l'apport technique de Ludovic Petit (atelier Veral)<br>et l'aide généreuse de Tirésias Mercier, Christophe Morin<br>et Paul Lugagne Delpon"
var des33 ="<img src='../../picts/triangle_black_small.png'>  <i>TUTEURS</i>, 2012<br>Sculptures<br>Métal, 2 barres téléscopiques dont l'intersection se situe à 157 cm<br>(correspondant à la hauteur de regard de l'artiste)<br>Avec le soutien du Palais de Tokyo<br><br><img src='../../picts/triangle_black_small.png'>  <i>APLOMB ET CERTITUDES</i>, 2012<br>Sculptures, 1/4<br>Câbles et chaînes métalliques, plombs<br>Avec le soutien du Palais de Tokyo"
var des34 ="<table width='100%' border='0' cellspacing='0' cellpadding='0'><tr><td class='text_11'><img src='../../picts/triangle_black_small.png'>&nbsp;&nbsp;<i>INSTRUCTIONS POUR POTENTIEL EXTRA SENSORIEL,<br>M&Eacute;THODE ET ENTRA&Icirc;NEMENT &Agrave; LA PRATIQUE AUTONOME<br>DE LA VOYANCE</i>, 2012<br>&Eacute;dition - livre<br>impression num&eacute;rique couleur sur papier Cyclus<br>32 pages, 100 exemplaires<br>Avec le soutien du Palais de Tokyo et l'aide g&eacute;n&eacute;reuse de Paul Lugagne Delpon</td></tr><tr><td class='spacer8'>&nbsp;</td></tr><tr><td class='text_11'><a class='link_light11' href='../../picts/2.pieces/34.instructions_pour_potentiel_extrasensoriel/clemencetorres_instructions_pour_potentiel_extrasensoriel_pages_1_a_10.pdf' target='_blank'><img src='../../picts/more.jpg' height='20'>&nbsp;&nbsp;T&eacute;l&eacute;charger un extrait du livre, pages 1 &agrave; 10</a></td></tr></table>"
var des35 ="<table width='100%' border='0' cellspacing='0' cellpadding='0'><tr><td class='text_11'><img src='../../picts/triangle_black_small.png'>&nbsp;&nbsp;<i>INSTRUCTIONS FOR EXTRASENSORY POTENTIAL,<br>METHOD AND TRAINING FOR THE AUTONOMOUS PRACTICE<br>OF CLAIRVOYANCE</i>, 2012<br>Book, digital color print, 32 pages<br>With the support of Flora Katz, Mikaela Assolent et Maia Asshaq<br>and the generous contribution of Danielle Aubert and Irene Wang</td></tr><tr><td class='spacer8'>&nbsp;</td></tr><tr><td class='text_11'><a class='link_light11' href='../../picts/2.pieces/34.instructions_pour_potentiel_extrasensoriel/clemencetorres_instructions_pour_potentiel_extrasensoriel_pages_1_a_10.pdf' target='_blank'><img src='../../picts/more.jpg' height='20'>&nbsp;&nbsp;Download an extract of the book, pages 1 to 10</a></td></tr></table>"

function changeText(idElement){
	document.getElementById('imagedescription').innerHTML =idElement;
}

// <img src="../../picts/triangle_black.jpg"