// Generated by CoffeeScript 1.7.1
(function() {
  $(function() {
    var sel, sel2, sideslider;
    $('.show-menu-button').click(function() {
      return $('.sidebar').toggleClass('active');
    });
    sideslider = $('[data-toggle=collapse-side]');
    sel = sideslider.attr('data-target');
    sel2 = sideslider.attr('data-target-2');
    return sideslider.click(function() {
      $(sel).toggleClass('in');
      return $(sel2).toggleClass('out');
    });
  });

}).call(this);

//# sourceMappingURL=app.map
