// Generated by CoffeeScript 1.7.1
(function() {
  $(function() {
    return $('.show-menu-button').click(function() {
      return $('.sidebar').toggleClass('active');
    });
  });

}).call(this);

//# sourceMappingURL=app.map
