// JavaScript Document

var des0 = ""
var des1 = "<table width='100%' border='0' cellspacing='0' cellpadding='0'><tr><td class='text_11'><img src='../../picts/triangle_black_small.png'>  <i>V=A<sup>3</sup></i>, 2009<br />Catalogue d'exposition collective, 60 exemplaires<br />Graphistes : Jonahtan Rouah, Thomas Baille<br />Tirage offset deux couleurs, 16 pages, 22,5 x 16 cm<br />Textes critiques écrits par/pour les artistes :<br>Agata Frydrych, Karolina Kazmierska et Clémence Torres</td></tr><tr><td class='spacer8'>&nbsp;</td></tr><tr><td class='text_11'><a class='link_light11' href='../../picts/3.publications/1.v_a3/clemencetorres_publications_va3_affiche.pdf' target='_blank'><img src='../../picts/more.jpg' height='20'>  Télécharger l'affiche</a></td></tr></table>";
var des2 = "<img src='../../picts/triangle_black_small.png'>  <i>RÉSONANCES BIENNALE DE LYON X</i>, 2009<br />Catalogue des manifestations culturelles<br />Exposition dans la galerie l'Atelier des ombres<br />pages 94 à 96";
var des3 = "<img src='../../picts/triangle_black_small.png'>  <i>LES ENFANTS DU SABBAT XI</i>, 2010<br />Coédition ENBA Lyon + ESA Clermont Communauté<br />+ Creux de l'enfer, Thiers<br />Catalogue d'exposition collective<br />collection «mes pas à faire au CREUX DE L'ENFER»<br />142 pages<br />Pages 106 à 117";
var des4 = "<table width='100%' border='0' cellspacing='0' cellpadding='0'><tr><td class='text_11'><img src='../../picts/triangle_black_small.png'>  <i>THE MAGNIFICIENT SEVEN</i>, 2010<br />Coédition ENBA Lyon + 55ème Salon de Montrouge<br />Catalogue d'exposition collective «The Magnificient seven»<br />50 pages, 21 x 21 cm<br />pages 12 à 17</td></tr><tr><td class='spacer8'>&nbsp;</td></tr><tr><td class='text_11'><a class='link_light11' href='../../picts/3.publications/4.magnificient_seven/clemencetorres_publications_the_magnificient_seven.pdf' target='_blank'><img src='../../picts/more.jpg' height='20'>  Télécharger le catalogue</a></td></tr></table>";
var des5 = "<table width='100%' border='0' cellspacing='0' cellpadding='0'><tr><td class='text_11'><img src='../../picts/triangle_black_small.png'>  <i>55ème SALON DE MONTROUGE</i>, 2010<br />Catalogue de la vente aux enchères<br />sous la conduite de Maître Pierre Cornette de St-Cyr et Stéphane Corréard<br /><br />Pièces 61 et 62 en vente :<br>61. <i>Façades, seconde</i><br>62. <i>Topologie d'un comportement extensible</i></td></tr><tr><td class='spacer8'>&nbsp;</td></tr><tr><td class='text_11'><a class='link_light11' href='../../picts/3.publications/5.vae_montrouge_(REMOVED)/clemencetorres_publications_catalogue_vente_aux_encheres_montrouge.pdf' target='_blank'><img src='../../picts/more.jpg' height='20'>  Télécharger le catalogue</a></td></tr></table>";
var des6 = "<img src='../../picts/triangle_black_small.png'>  <i>la revue nécessaire #2</i>, 2010<br />Édition<br />Le vivant-Vivant<br />dirigée par Guillaume du Boisbaudry, 192 pages<br />consultable et téléchargeable sur <a class='link_light11' href='http://necessaire.eu' target='_blank'>http://necessaire.eu</a><br /><br />Texte, <i>17 DES 253 VARIATIONS AUTOUR D'UNE EFFERVESCENCE ?</i>, 2009<br>pages 176 à 183";
var des7 ="<table width='100%' border='0' cellspacing='0' cellpadding='0'><tr><td class='text_11'><img src='../../picts/triangle_black_small.png'>&nbsp;&nbsp;<i>LIVRET IV et LIVRET V</i>, 2012<br>19 f&eacute;vrier - 10 juin 2011<br>Exposition collective pr&eacute;sent&eacute;e par Irmavep Club,<br>Mus&eacute;e d&eacute;partemental d'art contemporain, Ch&acirc;teau de Rochechouart<br>Publication r&eacute;alis&eacute;e par Irmavep Club avec les textes de Jack Cox, Alexandra Delage et Nicolas Exertier</td></tr><tr><td class='spacer8'>&nbsp;</td></tr><tr><td class='text_11'><a class='link_light11' href='../../picts/3.publications/7.Livret_IV/clemencetorres_publication_livretIV.pdf' target='_blank'><img src='../../picts/more.jpg' height='20'>&nbsp;&nbsp;T&eacute;l&eacute;charger l'édition complète</a></td></tr></table>"

function changeText(idElement){
	document.getElementById('imagedescription').innerHTML =idElement;
}

// <img src="../../picts/triangle_black.jpg"